// Auto-generated by gen_eob1_chinese.py
// Translations sourced from EOB1 EXE patch + manual edits
// Strings without translations are intentionally left in English as fallback

static const char *const kEoB1ChargenStrings1DOSChinese[9] = {
	"\xb6\xa4\xa5\xee\xa4\x77\xa7\xb9\xa6\xa8\xa1\x43\r\xbf\xef PLAY \xab\xf6\xb6\x73\r\xa9\xce\xab\xf6 P \xc1\xe4\r\xb6\x7d\xa9\x6c\xb9\x43\xc0\xb8\xa1\x43", /* "隊伍已完成。選按鈕或按鍵開始遊戲。" */
	"          ",
	"\xa8\xbe\r\xa9\x52\r\xaf\xc5", /* "防命級" */
	"%s\r%d\r%d\r%d\r%d\r%d",
	"%d\r%d",
	"%d",
	"%d/%d",
	"%d/%d/%d",
	"\xbf\xef\xa7\x41\xad\x6e\xab\xd8\xa5\xdf\r\xa9\xce\xc0\xcb\xb5\xf8\xaa\xba\r\xa8\xa4\xa6\xe2\xa4\xe8\xb6\xf4\xa1\x43", /* "選你要建立或檢視的角色方塊。" */
};

static const StringListProvider kEoB1ChargenStrings1DOSChineseProvider = { ARRAYSIZE(kEoB1ChargenStrings1DOSChinese), kEoB1ChargenStrings1DOSChinese };

static const char *const kEoB1ChargenStrings2DOSChinese[12] = {
	"%s",
	"%d",
	"%s",
	"%d",
	"%d",
	"%d",
	"%s",
	"%d",
	"\xbf\xef\xbe\xdc\xba\xd8\xb1\xda\xa1\x47", /* "選擇種族：" */
	"\xbf\xef\xbe\xdc\xc2\xbe\xb7\x7e\xa1\x47", /* "選擇職業：" */
	"\xbf\xef\xbe\xdc\xb0\x7d\xc0\xe7\xa1\x47", /* "選擇陣營：" */
	"\xa6\x57\xa1\x47", /* "名：" */
};

static const StringListProvider kEoB1ChargenStrings2DOSChineseProvider = { ARRAYSIZE(kEoB1ChargenStrings2DOSChinese), kEoB1ChargenStrings2DOSChinese };

static const char *const kEoB1ChargenStatStringsDOSChinese[12] = {
	"\xa4\x4f", /* "力" */
	"\xb4\xbc", /* "智" */
	"\xbc\x7a", /* "慧" */
	"\xb1\xd3", /* "敏" */
	"\xc5\xe9", /* "體" */
	"\xbe\x79", /* "魅" */
	"\xa4\x4f\xb6\x71", /* "力量" */
	"\xb4\xbc\xa4\x4f", /* "智力" */
	"\xb4\xbc\xbc\x7a", /* "智慧" */
	"\xb1\xd3\xb1\xb6", /* "敏捷" */
	"\xc5\xe9\xbd\xe8", /* "體質" */
	"\xbe\x79\xa4\x4f", /* "魅力" */
};

static const StringListProvider kEoB1ChargenStatStringsDOSChineseProvider = { ARRAYSIZE(kEoB1ChargenStatStringsDOSChinese), kEoB1ChargenStatStringsDOSChinese };

static const char *const kEoB1ChargenRaceSexStringsDOSChinese[12] = {
	"\xa4\x48\xc3\xfe\xa8\x6b", /* "人類男" */
	"\xa4\x48\xc3\xfe\xa4\x6b", /* "人類女" */
	"\xba\xeb\xc6\x46\xa8\x6b", /* "精靈男" */
	"\xba\xeb\xc6\x46\xa4\x6b", /* "精靈女" */
	"\xa5\x62\xba\xeb\xc6\x46\xa8\x6b", /* "半精靈男" */
	"\xa5\x62\xba\xeb\xc6\x46\xa4\x6b", /* "半精靈女" */
	"\xb8\x47\xa4\x48\xa8\x6b", /* "矮人男" */
	"\xb8\x47\xa4\x48\xa4\x6b", /* "矮人女" */
	"\xa6\x61\xba\xeb\xa8\x6b", /* "地精男" */
	"\xa6\x61\xba\xeb\xa4\x6b", /* "地精女" */
	"\xa5\x62\xa4\x48\xa8\x6b", /* "半人男" */
	"\xa5\x62\xa4\x48\xa4\x6b", /* "半人女" */
};

static const StringListProvider kEoB1ChargenRaceSexStringsDOSChineseProvider = { ARRAYSIZE(kEoB1ChargenRaceSexStringsDOSChinese), kEoB1ChargenRaceSexStringsDOSChinese };

static const char *const kEoB1ChargenClassStringsDOSChinese[21] = {
	"\xbe\xd4\xa4\x68", /* "戰士" */
	"\xb9\x43\xab\x4c", /* "遊俠" */
	"\xb8\x74\xc3\x4d", /* "聖騎" */
	"\xaa\x6b\xae\x76", /* "法師" */
	"\xaa\xaa\xae\x76", /* "牧師" */
	"\xb5\x73\xb8\xe9", /* "盜賊" */
	"\xbe\xd4\xa1\x4d\xaa\xaa", /* "戰／牧" — BUG-007 fix: fullwidth slash */
	"\xbe\xd4\xa1\x4d\xb5\x73", /* "戰／盜" */
	"\xbe\xd4\xa1\x4d\xaa\x6b", /* "戰／法" */
	"\xbe\xd4\xaa\x6b\xb5\x73", /* "戰法盜" — tri-class, no slash */
	"\xb5\x73\xa1\x4d\xaa\x6b", /* "盜／法" */
	"\xaa\xaa\xa1\x4d\xb5\x73", /* "牧／盜" */
	"\xbe\xd4\xaa\xaa\xaa\x6b", /* "戰牧法" — tri-class */
	"\xab\x4c\xa1\x4d\xaa\xaa", /* "俠／牧" */
	"\xaa\xaa\xa1\x4d\xaa\x6b", /* "牧／法" */
	"\xbe\xd4\xa4\x68", /* "戰士" */
	"\xaa\x6b\xae\x76", /* "法師" */
	"\xaa\xaa\xae\x76", /* "牧師" */
	"\xb5\x73\xb8\xe9", /* "盜賊" */
	"\xb8\x74\xc3\x4d", /* "聖騎" */
	"\xb9\x43\xab\x4c", /* "遊俠" */
};

static const StringListProvider kEoB1ChargenClassStringsDOSChineseProvider = { ARRAYSIZE(kEoB1ChargenClassStringsDOSChinese), kEoB1ChargenClassStringsDOSChinese };

static const char *const kEoB1ChargenAlignmentStringsDOSChinese[9] = {
	"\xa6\x75\xa7\xc7\xb5\xbd\xa8\x7d", /* "守序善良" */
	"\xa4\xa4\xa5\xdf\xb5\xbd\xa8\x7d", /* "中立善良" */
	"\xb2\x56\xb6\xc3\xb5\xbd\xa8\x7d", /* "混亂善良" */
	"\xa6\x75\xa7\xc7\xa4\xa4\xa5\xdf", /* "守序中立" */
	"\xb5\xb4\xb9\xef\xa4\xa4\xa5\xdf", /* "絕對中立" */
	"\xb2\x56\xb6\xc3\xa4\xa4\xa5\xdf", /* "混亂中立" */
	"\xa6\x75\xa7\xc7\xa8\xb8\xb4\x63", /* "守序邪惡" */
	"\xa4\xa4\xa5\xdf\xa8\xb8\xb4\x63", /* "中立邪惡" */
	"\xb2\x56\xb6\xc3\xa8\xb8\xb4\x63", /* "混亂邪惡" */
};

static const StringListProvider kEoB1ChargenAlignmentStringsDOSChineseProvider = { ARRAYSIZE(kEoB1ChargenAlignmentStringsDOSChinese), kEoB1ChargenAlignmentStringsDOSChinese };

static const char *const kEoB1ChargenEnterGameStringsDOSChinese[1] = {
	"  \xb6\x69\xa4\x4a\xb9\x43\xc0\xb8\xa1\x43\r  \xbd\xd0\xb5\x79\xad\xd4\xa1\x43", /* "進入遊戲。請稍候。" */
};

static const StringListProvider kEoB1ChargenEnterGameStringsDOSChineseProvider = { ARRAYSIZE(kEoB1ChargenEnterGameStringsDOSChinese), kEoB1ChargenEnterGameStringsDOSChinese };

static const char *const kEoB1MainMenuStringsDOSChinese[3] = {
	"\xb8\xfc\xa4\x4a\xb6\x69\xa6\xe6\xa4\xa4\xb9\x43\xc0\xb8\r", /* "載入進行中遊戲" */
	"\xb6\x7d\xa9\x6c\xb7\x73\xb6\xa4\xa5\xee\r", /* "開始新隊伍" */
	"\xc2\xf7\xb6\x7d\r", /* "離開" */
};

static const StringListProvider kEoB1MainMenuStringsDOSChineseProvider = { ARRAYSIZE(kEoB1MainMenuStringsDOSChinese), kEoB1MainMenuStringsDOSChinese };

static const char *const kEoB1BonusStringsDOSChinese[3] = {
	"\xae\xa5\xb3\xdf\xa7\xb9\xa6\xa8\xa5\xfe\xb3\xa1 12 \xad\xd3 Beholder \xbc\xfa\xc0\x79\xa1\x43\r\r\xa7\x41\xc0\xf2\xb3\xd3\xb6\xa4\xa5\xee\xa8\xa4\xa6\xe2\xa6\x57\xb3\xe6\xa1\x47\r\r", /* "恭喜完成全部個獎勵。你獲勝隊伍角色名單：" */
	"\r",
	"\r\r\xb1\x4b\xbd\x58\xa1\x47%04x\r", /* "密碼：" */
};

static const StringListProvider kEoB1BonusStringsDOSChineseProvider = { ARRAYSIZE(kEoB1BonusStringsDOSChinese), kEoB1BonusStringsDOSChinese };

static const char *const kEoB1TurnUndeadStringDOSChinese[1] = {
	"\x06\x06%s uses the power to turn undead!\x06\x0f\r",
};

static const StringListProvider kEoB1TurnUndeadStringDOSChineseProvider = { ARRAYSIZE(kEoB1TurnUndeadStringDOSChinese), kEoB1TurnUndeadStringDOSChinese };

static const char *const kEoB1Npc0StringsDOSChinese[2] = {
	"\r         \xaf\xac\xa7\x41\xae\xc8\xb3\x7e\xb6\xb6\xa7\x51\xa1\x43", /* "祝你旅途順利。" */
	"\xbf\xef\xbe\xdc\xad\x6e\xb4\x5f\xac\xa1\xbd\xd6\xa1\x48", /* "選擇要復活誰？" */
};

static const StringListProvider kEoB1Npc0StringsDOSChineseProvider = { ARRAYSIZE(kEoB1Npc0StringsDOSChinese), kEoB1Npc0StringsDOSChinese };

static const char *const kEoB1Npc11StringsDOSChinese[3] = {
	"\xaa\x76\xc0\xf8\xb6\xcb\xb6\xd5", /* "治療傷勢" */
	"\xa5\xe6\xbd\xcd", /* "交談" */
	"\xc2\xf7\xb6\x7d", /* "離開" */
};

static const StringListProvider kEoB1Npc11StringsDOSChineseProvider = { ARRAYSIZE(kEoB1Npc11StringsDOSChinese), kEoB1Npc11StringsDOSChinese };

static const char *const kEoB1Npc12StringsDOSChinese[2] = {
	"\xaa\x76\xc0\xf8\xb6\xcb\xb6\xd5", /* "治療傷勢" */
	"\xc2\xf7\xb6\x7d", /* "離開" */
};

static const StringListProvider kEoB1Npc12StringsDOSChineseProvider = { ARRAYSIZE(kEoB1Npc12StringsDOSChinese), kEoB1Npc12StringsDOSChinese };

static const char *const kEoB1Npc21StringsDOSChinese[2] = {
	"\xc5\xa5\xa5\x4c\xb4\xa3\xc4\xb3", /* "聽他提議" */
	"\xc2\xf7\xb6\x7d", /* "離開" */
};

static const StringListProvider kEoB1Npc21StringsDOSChineseProvider = { ARRAYSIZE(kEoB1Npc21StringsDOSChinese), kEoB1Npc21StringsDOSChinese };

static const char *const kEoB1Npc22StringsDOSChinese[2] = {
	"\xc0\xb0\xa7\x55\xa5\x4c", /* "幫助他" */
	"\xc2\xf7\xb6\x7d", /* "離開" */
};

static const StringListProvider kEoB1Npc22StringsDOSChineseProvider = { ARRAYSIZE(kEoB1Npc22StringsDOSChinese), kEoB1Npc22StringsDOSChinese };

static const char *const kEoB1Npc31StringsDOSChinese[2] = {
	"\xaa\x76\xc0\xf8\xb6\xa4\xa5\xee", /* "治療隊伍" */
	"\xc2\xf7\xb6\x7d", /* "離開" */
};

static const StringListProvider kEoB1Npc31StringsDOSChineseProvider = { ARRAYSIZE(kEoB1Npc31StringsDOSChinese), kEoB1Npc31StringsDOSChinese };

static const char *const kEoB1Npc32StringsDOSChinese[3] = {
	"\xaa\x76\xc0\xf8\xb6\xa4\xa5\xee", /* "治療隊伍" */
	"\xb4\x5f\xac\xa1\xa6\xba\xaa\xcc", /* "復活死者" */
	"\xc2\xf7\xb6\x7d", /* "離開" */
};

static const StringListProvider kEoB1Npc32StringsDOSChineseProvider = { ARRAYSIZE(kEoB1Npc32StringsDOSChinese), kEoB1Npc32StringsDOSChinese };

static const char *const kEoB1Npc4StringsDOSChinese[2] = {
	"\xa7\xf0\xc0\xbb", /* "攻擊" */
	"\xb8\xec\xb8\xef", /* "賄賂" */
};

static const StringListProvider kEoB1Npc4StringsDOSChineseProvider = { ARRAYSIZE(kEoB1Npc4StringsDOSChinese), kEoB1Npc4StringsDOSChinese };

static const char *const kEoB1Npc5StringsDOSChinese[3] = {
	"\xb1\xfe\xa4\x46\xa6\x6f", /* "殺了她" */
	"\xc5\xa5\xa6\x6f\xbb\xa1", /* "聽她說" */
	"\xa9\xf1\xa6\x6f\xa8\xab", /* "放她走" */
};

static const StringListProvider kEoB1Npc5StringsDOSChineseProvider = { ARRAYSIZE(kEoB1Npc5StringsDOSChinese), kEoB1Npc5StringsDOSChinese };

static const char *const kEoB1Npc6StringsDOSChinese[2] = {
	"\xa7\xeb\xad\xb0", /* "投降" */
	"\xa7\xf0\xc0\xbb", /* "攻擊" */
};

static const StringListProvider kEoB1Npc6StringsDOSChineseProvider = { ARRAYSIZE(kEoB1Npc6StringsDOSChinese), kEoB1Npc6StringsDOSChinese };

static const char *const kEoB1Npc7StringsDOSChinese[3] = {
	"\xc4\xc0\xa9\xf1\xa5\x4c", /* "釋放他" */
	"\xb1\xfe\xa4\x46\xa5\x4c", /* "殺了他" */
	"\xc2\xf7\xb6\x7d", /* "離開" */
};

static const StringListProvider kEoB1Npc7StringsDOSChineseProvider = { ARRAYSIZE(kEoB1Npc7StringsDOSChinese), kEoB1Npc7StringsDOSChinese };

static const char *const kEoB1PryDoorStringsDOSChinese[7] = {
	"\xb5\x4c\xa4\x48\xaf\xe0\xb1\x6a\xa6\xe6\xa5\xb4\xb6\x7d\xaa\xf9\xa1\x43\r", /* "無人能強行打開門。" */
	"\xb6\xa4\xa5\xee\xb1\x6a\xa6\xe6\xa5\xb4\xb6\x7d\xaa\xf9\xa1\x43\r", /* "隊伍強行打開門。" */
	"%s \xb1\x6a\xa6\xe6\xa5\xb4\xb6\x7d\xaa\xf9\xa1\x49\r", /* "強行打開門！" */
	"\xb6\xa4\xa5\xee\xb8\xd5\xb9\xcf\xb1\x6a\xb6\x7d\xaa\xf9\xa5\xa2\xb1\xd1\xa1\x43\r", /* "隊伍試圖強開門失敗。" */
	"\xb5\x4c\xaa\x6b\xa7\xe2\xb8\xd3\xaa\xab\xab\x7e\xa9\xf1\xa8\xba\xb8\xcc\xa1\x43\r", /* "無法把該物品放那裡。" */
	"\xaa\xab\xab\x7e\xb9\x4c\xa4\x6a\xb5\x4c\xaa\x6b\xa9\xf1\xa4\x4a\xa1\x43\r", /* "物品過大無法放入。" */
	"\xb5\x4c\xa4\x48\xaf\xe0\xbc\xc0\xb6\x7d\xa6\xb9\xaa\xf9\xa1\x43\r", /* "無人能撬開此門。" */
};

static const StringListProvider kEoB1PryDoorStringsDOSChineseProvider = { ARRAYSIZE(kEoB1PryDoorStringsDOSChinese), kEoB1PryDoorStringsDOSChinese };

static const char *const kEoB1WarningStringsDOSChinese[3] = {
	"\xb5\x4c\xaa\x6b\xb4\xc2\xa8\xba\xad\xd3\xa4\xe8\xa6\x56\xa8\xab\xa1\x43\r", /* "無法朝那個方向走。" */
	"%s \xb5\x4c\xaa\x6b\xb6\x69\xad\xb9\xa1\x49\r", /* "無法進食！" */
	"\xa5\x75\xaf\xe0\xa6\x59\xad\xb9\xaa\xab\xa1\x49\r", /* "只能吃食物！" */
};

static const StringListProvider kEoB1WarningStringsDOSChineseProvider = { ARRAYSIZE(kEoB1WarningStringsDOSChinese), kEoB1WarningStringsDOSChinese };

static const char *const kEoB1ItemSuffixStringsRingsDOSChinese[4] = {
	"\xb9\xa2\xab\x7e", /* "飾品" */
	"\xaa\x6b\xb3\x4e", /* "法術" */
	"\xad\xb9\xaa\xab", /* "食物" */
	"\xa6\xd0\xb8\xa8", /* "羽落" */
};

static const StringListProvider kEoB1ItemSuffixStringsRingsDOSChineseProvider = { ARRAYSIZE(kEoB1ItemSuffixStringsRingsDOSChinese), kEoB1ItemSuffixStringsRingsDOSChinese };

static const char *const kEoB1ItemSuffixStringsPotionsDOSChinese[8] = {
	"\xa5\xa8\xa4\x48\xa4\xa7\xa4\x4f", /* "巨人之力" */
	"\xaa\x76\xc0\xf8", /* "治療" */
	"\xb1\x6a\xae\xc4\xaa\x76\xc0\xf8", /* "強效治療" */
	"\xac\x72\xc3\xc4", /* "毒藥" */
	"\xac\xa1\xa4\x4f", /* "活力" */
	"\xb3\x74\xab\xd7", /* "速度" */
	"\xc1\xf4\xa7\xce", /* "隱形" */
	"\xb8\xd1\xac\x72", /* "解毒" */
};

static const StringListProvider kEoB1ItemSuffixStringsPotionsDOSChineseProvider = { ARRAYSIZE(kEoB1ItemSuffixStringsPotionsDOSChinese), kEoB1ItemSuffixStringsPotionsDOSChinese };

static const char *const kEoB1ItemSuffixStringsWandsDOSChinese[7] = {
	"\xb4\xce", /* "棒" */
	"\xb0\x7b\xb9\x71", /* "閃電" */
	"\xa6\x42\xc1\xf7", /* "冰霜" */
	"\xaa\x76\xc2\xa1", /* "治癒" */
	"\xa4\xf5\xb2\x79\xb3\x4e", /* "火球術" */
	"\xa7\xc6\xba\xb8\xba\xfb\xa8\xc8", /* "希爾維亞" */
	"\xc5\x5d\xaa\x6b\xad\xb8\xbc\x75", /* "魔法飛彈" */
};

static const StringListProvider kEoB1ItemSuffixStringsWandsDOSChineseProvider = { ARRAYSIZE(kEoB1ItemSuffixStringsWandsDOSChinese), kEoB1ItemSuffixStringsWandsDOSChinese };

static const char *const kEoB1RipItemStringsDOSChinese[3] = {
	"%s \xa5\xa2\xa5\x68\xa6\x6f\xaa\xba ", /* "失去她的" */
	"%s \xa5\xa2\xa5\x68\xa5\x4c\xaa\xba ", /* "失去他的" */
	"\xa1\x43\r", /* "。" */
};

static const StringListProvider kEoB1RipItemStringsDOSChineseProvider = { ARRAYSIZE(kEoB1RipItemStringsDOSChinese), kEoB1RipItemStringsDOSChinese };

static const char *const kEoB1CursedStringDOSChinese[1] = {
	"\xb6\x41\xa9\x47 %s %d", /* "詛咒" */
};

static const StringListProvider kEoB1CursedStringDOSChineseProvider = { ARRAYSIZE(kEoB1CursedStringDOSChinese), kEoB1CursedStringDOSChinese };

static const char *const kEoB1MagicObjectStringsDOSChinese[5] = {
	"\xaa\x6b\xa8\xf7", /* "法卷" */
	"\xaa\xaa\xa8\xf7", /* "牧卷" */
	"\xa7\xd9\xab\xfc", /* "戒指" */
	"\xc3\xc4\xa4\xf4", /* "藥水" */
	"\xc5\x5d\xa7\xfa", /* "魔杖" */
};

static const StringListProvider kEoB1MagicObjectStringsDOSChineseProvider = { ARRAYSIZE(kEoB1MagicObjectStringsDOSChinese), kEoB1MagicObjectStringsDOSChinese };

static const char *const kEoB1MagicObjectString5DOSChinese[1] = {
	"\xb4\xce", /* "棒" */
};

static const StringListProvider kEoB1MagicObjectString5DOSChineseProvider = { ARRAYSIZE(kEoB1MagicObjectString5DOSChinese), kEoB1MagicObjectString5DOSChinese };

static const char *const kEoB1PatternSuffixDOSChinese[1] = {
	"%s \xaa\xba %s", /* "的" */
};

static const StringListProvider kEoB1PatternSuffixDOSChineseProvider = { ARRAYSIZE(kEoB1PatternSuffixDOSChinese), kEoB1PatternSuffixDOSChinese };

static const char *const kEoB1PatternGrFix1DOSChinese[1] = {
	"%s \xaa\xba %s", /* "的" */
};

static const StringListProvider kEoB1PatternGrFix1DOSChineseProvider = { ARRAYSIZE(kEoB1PatternGrFix1DOSChinese), kEoB1PatternGrFix1DOSChinese };

static const char *const kEoB1PatternGrFix2DOSChinese[1] = {
	"%s \xaa\xba %s", /* "的" */
};

static const StringListProvider kEoB1PatternGrFix2DOSChineseProvider = { ARRAYSIZE(kEoB1PatternGrFix2DOSChinese), kEoB1PatternGrFix2DOSChinese };

static const char *const kEoB1ValidateArmorStringDOSChinese[1] = {
	"%s\xa4\xa3\xaf\xe0\xac\xef\xc0\xb9\xa6\xb9\xc3\xfe\xb2\xaf\xa5\xd2\xa1\x43\r", /* "不能穿戴此類盔甲。" */
};

static const StringListProvider kEoB1ValidateArmorStringDOSChineseProvider = { ARRAYSIZE(kEoB1ValidateArmorStringDOSChinese), kEoB1ValidateArmorStringDOSChinese };

static const char *const kEoB1ValidateNoDropStringDOSChinese[1] = {
	"\xa4\xa3\xaf\xe0\xb1\x4e\xaa\xab\xab\x7e\xa9\xf1\xa6\x62\xa8\xba\xb8\xcc\xa1\x43\r", /* "不能將物品放在那裡。" */
};

static const StringListProvider kEoB1ValidateNoDropStringDOSChineseProvider = { ARRAYSIZE(kEoB1ValidateNoDropStringDOSChinese), kEoB1ValidateNoDropStringDOSChinese };

static const char *const kEoB1PotionStringsDOSChinese[2] = {
	"\xa4\xa4\xac\x72", /* "中毒" */
	"%s \xb7\x50\xc4\xb1 %s\xa1\x49\r", /* "感覺！" */
};

static const StringListProvider kEoB1PotionStringsDOSChineseProvider = { ARRAYSIZE(kEoB1PotionStringsDOSChinese), kEoB1PotionStringsDOSChinese };

static const char *const kEoB1WandStringsDOSChinese[2] = {
	"\xc5\x5d\xa7\xfa\xa8\x53\xa6\xb3\xa9\xfa\xc5\xe3\xae\xc4\xaa\x47\r", /* "魔杖沒有明顯效果" */
	"\xb5\x4c\xae\xc4\xaa\x47\xa1\x43\r", /* "無效果。" */
};

static const StringListProvider kEoB1WandStringsDOSChineseProvider = { ARRAYSIZE(kEoB1WandStringsDOSChinese), kEoB1WandStringsDOSChinese };

static const char *const kEoB1ItemMisuseStringsDOSChinese[3] = {
	"%s\xb5\x4c\xaa\x6b\xa8\xcf\xa5\xce\xa6\xb9\xaa\xab\xab\x7e\xa1\x43\r", /* "無法使用此物品。" */
	"\xa6\xb9\xaa\xab\xab\x7e\xac\xef\xc0\xb9\xae\xc9\xa6\xdb\xb0\xca\xa8\xcf\xa5\xce\xa1\x43\r", /* "此物品穿戴時自動使用。" */
	"\xa6\xb9\xaa\xab\xab\x7e\xa4\xa3\xaf\xe0\xb3\x6f\xbc\xcb\xa8\xcf\xa5\xce\xa1\x43\r", /* "此物品不能這樣使用。" */
};

static const StringListProvider kEoB1ItemMisuseStringsDOSChineseProvider = { ARRAYSIZE(kEoB1ItemMisuseStringsDOSChinese), kEoB1ItemMisuseStringsDOSChinese };

static const char *const kEoB1TakenStringsDOSChinese[1] = {
	" \xa4\x77\xae\xb3\xa1\x43\r", /* "已拿。" */
};

static const StringListProvider kEoB1TakenStringsDOSChineseProvider = { ARRAYSIZE(kEoB1TakenStringsDOSChinese), kEoB1TakenStringsDOSChinese };

static const char *const kEoB1PotionEffectStringsDOSChinese[8] = {
	"\xb1\x6a\xa7\xa7\xb3\x5c\xa6\x68", /* "強壯許多" */
	"\xa6\x6e\xa8\xc7", /* "好些" */
	"\xa6\x6e\xab\xdc\xa6\x68", /* "好很多" */
	"\xbc\xc8\xae\xc9\xa4\xa3\xbe\x41", /* "暫時不適" */
	"\xa4\xa3\xa6\x41\xb0\xa7\xbe\x6a", /* "不再飢餓" */
	"\xb1\xd3\xb1\xb6\xa8\xb3\xb3\x74", /* "敏捷迅速" */
	"\xb3\x7a\xa9\xfa", /* "透明" */
	"\xa6\x6e\xa8\xc7", /* "好些" */
};

static const StringListProvider kEoB1PotionEffectStringsDOSChineseProvider = { ARRAYSIZE(kEoB1PotionEffectStringsDOSChinese), kEoB1PotionEffectStringsDOSChinese };

static const char *const kEoB1YesNoStringsDOSChinese[2] = {
	"\xac\x4f", /* "是" */
	"\xa7\x5f", /* "否" */
};

static const StringListProvider kEoB1YesNoStringsDOSChineseProvider = { ARRAYSIZE(kEoB1YesNoStringsDOSChinese), kEoB1YesNoStringsDOSChinese };

static const char *const kEoB1MoreStringsDOSChinese[1] = {
	"\xc4\x7e\xc4\xf2", /* "繼續" */
};

static const StringListProvider kEoB1MoreStringsDOSChineseProvider = { ARRAYSIZE(kEoB1MoreStringsDOSChinese), kEoB1MoreStringsDOSChinese };

static const char *const kEoB1NpcMaxStringsDOSChinese[1] = {
	"\xb6\xa4\xa5\xee\xb3\xcc\xa6\x68\xa4\xbb\xa6\xec\xa8\xa4\xa6\xe2\xa1\x43\xbd\xd0\xbf\xef\xbe\xdc\xad\x6e\xbd\xf0\xa5\x58\xaa\xba\xa8\xa4\xa6\xe2\xa1\x43", /* "隊伍最多六位角色。請選擇要踢出的角色。" */
};

static const StringListProvider kEoB1NpcMaxStringsDOSChineseProvider = { ARRAYSIZE(kEoB1NpcMaxStringsDOSChinese), kEoB1NpcMaxStringsDOSChinese };

static const char *const kEoB1NpcJoinStringsDOSChinese[1] = {
	"%s \xa5\x5b\xa4\x4a\xb6\xa4\xa5\xee\xa1\x43\r", /* "加入隊伍。" */
};

static const StringListProvider kEoB1NpcJoinStringsDOSChineseProvider = { ARRAYSIZE(kEoB1NpcJoinStringsDOSChinese), kEoB1NpcJoinStringsDOSChinese };

static const char *const kEoB1CancelStringsDOSChinese[1] = {
	"\xa8\xfa\xae\xf8", /* "取消" */
};

static const StringListProvider kEoB1CancelStringsDOSChineseProvider = { ARRAYSIZE(kEoB1CancelStringsDOSChinese), kEoB1CancelStringsDOSChinese };

static const char *const kEoB1MenuStringsMainDOSChinese[8] = {
	"\xbf\xef\xbe\xdc\xa1\x47", /* "選擇：" */
	"\xa5\xf0\xae\xa7\xb6\xa4\xa5\xee", /* "休息隊伍" */
	"\xb0\x4f\xbe\xd0\xaa\x6b\xb3\x4e", /* "記憶法術" */
	"\xac\xe8\xc3\xab\xaa\x6b\xb3\x4e", /* "祈禱法術" */
	"\xc1\xc3\xbc\x67\xa8\xf7\xb6\x62", /* "謄寫卷軸" */
	"\xb0\xbe\xa6\x6e\xb3\x5d\xa9\x77", /* "偏好設定" */
	"\xb9\x43\xc0\xb8\xbf\xef\xb6\xb5", /* "遊戲選項" */
	"\xc2\xf7\xb6\x7d", /* "離開" */
};

static const StringListProvider kEoB1MenuStringsMainDOSChineseProvider = { ARRAYSIZE(kEoB1MenuStringsMainDOSChinese), kEoB1MenuStringsMainDOSChinese };

static const char *const kEoB1MenuStringsSaveLoadDOSChinese[8] = {
	"\xb8\xfc\xa4\x4a\xb9\x43\xc0\xb8", /* "載入遊戲" */
	"\xc0\x78\xa6\x73\xb9\x43\xc0\xb8", /* "儲存遊戲" */
	"\xbd\xf0\xa5\x58\xa8\xa4\xa6\xe2", /* "踢出角色" */
	"\xc2\xf7\xb6\x7d\xb9\x43\xc0\xb8", /* "離開遊戲" */
	"\xb9\x43\xc0\xb8\xbf\xef\xb6\xb5\xa1\x47", /* "遊戲選項：" */
	"\r  \xa4\x77\xa6\x73\xc0\xc9\xa1\x43", /* "已存檔。" */
	"\r\xc0\x78\xa6\x73\xb9\x43\xc0\xb8\r \xa5\xa2\xb1\xd1\xa1\x49", /* "儲存遊戲失敗！" */
	"\r\xb8\xfc\xa4\x4a\xb9\x43\xc0\xb8\r \xa5\xa2\xb1\xd1\xa1\x49", /* "載入遊戲失敗！" */
};

static const StringListProvider kEoB1MenuStringsSaveLoadDOSChineseProvider = { ARRAYSIZE(kEoB1MenuStringsSaveLoadDOSChinese), kEoB1MenuStringsSaveLoadDOSChinese };

static const char *const kEoB1MenuStringsOnOffDOSChinese[2] = {
	"\xb6\x7d", /* "開" */
	"\xc3\xf6", /* "關" */
};

static const StringListProvider kEoB1MenuStringsOnOffDOSChineseProvider = { ARRAYSIZE(kEoB1MenuStringsOnOffDOSChinese), kEoB1MenuStringsOnOffDOSChinese };

static const char *const kEoB1MenuStringsSpellsDOSChinese[17] = {
	"\r\r \xb1\x71\xb6\xa4\xa5\xee\xa4\xa4\xbf\xef\xa4\x40\xa6\xec\r \xb7\x51\xad\x6e\xbe\xc7\xb2\xdf\r \xaa\x6b\xb3\x4e\xaa\xba\xa8\xa4\xa6\xe2\xa1\x43", /* "從隊伍中選一位想要學習法術的角色。" */
	"\r \xa7\x41\xaa\xba\xb8\x74\xc3\x4d\xa4\x68\r \xb5\xa5\xaf\xc5\xa4\xd3\xa7\x43\r \xb5\x4c\xaa\x6b\xac\x49\xaa\x6b\xa1\x43", /* "你的聖騎士等級太低無法施法。" */
	"\r\r \xaa\x6b\xae\x76\xa8\x53\xa6\xb3\r \xaa\x6b\xb3\x4e\xae\xd1\xa1\x49", /* "法師沒有法術書！" */
	"\r\r\r \xb1\x71\xb6\xa4\xa5\xee\xa4\xa4\xbf\xef\xa4\x40\xa6\xec\r \xb7\x51\xad\x6e\xac\xe8\xc3\xab\r \xa8\xfa\xb1\x6f\xaa\x6b\xb3\x4e\xaa\xba\xa8\xa4\xa6\xe2\xa1\x43", /* "從隊伍中選一位想要祈禱取得法術的角色。" */
	"\r \xb6\xa4\xa5\xee\xa4\xa4\xa8\x53\xa6\xb3\r \xaf\xe0\xac\xe8\xc3\xab\xaa\xba\r \xaa\xaa\xae\x76\xa1\x43", /* "隊伍中沒有能祈禱的牧師。" */
	"\r \xb6\xa4\xa5\xee\xa4\xa4\xa8\x53\xa6\xb3\r \xaf\xe0\xbe\xc7\xaa\x6b\xb3\x4e\r \xaa\xba\xaa\x6b\xae\x76\xa1\x43", /* "隊伍中沒有能學法術的法師。" */
	" \xa9\xfc\xb0\x67\xa9\xce\xa6\xba\xa4\x60\r \xaa\xba\xaa\x6b\xae\x76\xb5\x4c\xaa\x6b\r \xb0\x4f\xbe\xd0\xaa\x6b\xb3\x4e\xa1\x43", /* "昏迷或死亡的法師無法記憶法術。" */
	" \xa9\xfc\xb0\x67\xa9\xce\xa6\xba\xa4\x60\r \xaa\xba\xaa\xaa\xae\x76\xb5\x4c\xaa\x6b\r \xac\xe8\xc3\xab\xaa\x6b\xb3\x4e\xa1\x43", /* "昏迷或死亡的牧師無法祈禱法術。" */
	"1",
	"2",
	"3",
	"4",
	"5",
	"\xb2\x4d\xaa\xc5", /* "清空" */
	"\xa5\x69\xa5\xce\xaa\x6b\xb3\x4e\xa1\x47", /* "可用法術：" */
	"\xac\x4f", /* "是" */
	"\xa7\x5f", /* "否" */
};

static const StringListProvider kEoB1MenuStringsSpellsDOSChineseProvider = { ARRAYSIZE(kEoB1MenuStringsSpellsDOSChinese), kEoB1MenuStringsSpellsDOSChinese };

static const char *const kEoB1MenuStringsRestDOSChinese[5] = {
	"\r\xaa\x76\xc0\xf8\xae\x76\xad\x6e\r\xaa\x76\xc0\xf8\xb6\xa4\xa5\xee\xb6\xdc\xa1\x48", /* "治療師要治療隊伍嗎？" */
	" \xa6\xb3\xa4\x48\xa8\xfc\xb6\xcb\xa1\x43\r \xad\x6e\xa5\xf0\xae\xa7\xa8\xec\r \xb2\xac\xc2\xa1\xb6\xdc\xa1\x48", /* "有人受傷。要休息到痊癒嗎？" */
	"\xa5\xf0\xae\xa7\xa4\xa4\xa1\x43", /* "休息中。" */
	"\r \xa9\xd2\xa6\xb3\xa8\xa4\xa6\xe2\xb3\xa3\r \xa4\x77\xa7\xb9\xa5\xfe\xa5\xf0\xae\xa7\xa1\x43", /* "所有角色都已完全休息。" */
	" \xb6\xa4\xa5\xee\xbb\xdd\xad\x6e\xa5\xf0\xae\xa7\r \xa4\x7e\xaf\xe0\xa8\xfa\xb1\x6f\r \xaa\x6b\xb3\x4e\xa1\x43", /* "隊伍需要休息才能取得法術。" */
};

static const StringListProvider kEoB1MenuStringsRestDOSChineseProvider = { ARRAYSIZE(kEoB1MenuStringsRestDOSChinese), kEoB1MenuStringsRestDOSChinese };

static const char *const kEoB1MenuStringsDropDOSChinese[1] = {
	" \xa8\xa4\xa6\xe2\xa4\xa3\xaf\xe0\r \xa4\xd6\xa9\xf3\xa5\x7c\xa6\xec\xa1\x43", /* "角色不能少於四位。" */
};

static const StringListProvider kEoB1MenuStringsDropDOSChineseProvider = { ARRAYSIZE(kEoB1MenuStringsDropDOSChinese), kEoB1MenuStringsDropDOSChinese };

static const char *const kEoB1MenuStringsExitDOSChinese[1] = {
	" \xbd\x54\xa9\x77\xad\x6e\r \xc2\xf7\xb6\x7d\xb9\x43\xc0\xb8\xb6\xdc\xa1\x48", /* "確定要離開遊戲嗎？" */
};

static const StringListProvider kEoB1MenuStringsExitDOSChineseProvider = { ARRAYSIZE(kEoB1MenuStringsExitDOSChinese), kEoB1MenuStringsExitDOSChinese };

static const char *const kEoB1MenuStringsStarveDOSChinese[1] = {
	" \xb6\xa4\xa5\xee\xa5\xbf\xa6\x62\r \xb0\xa7\xbe\x6a\xa1\x43\xad\x6e\xc4\x7e\xc4\xf2\r \xa5\xf0\xae\xa7\xb6\xdc\xa1\x48", /* "隊伍正在飢餓。要繼續休息嗎？" */
};

static const StringListProvider kEoB1MenuStringsStarveDOSChineseProvider = { ARRAYSIZE(kEoB1MenuStringsStarveDOSChinese), kEoB1MenuStringsStarveDOSChinese };

static const char *const kEoB1MenuStringsScribeDOSChinese[5] = {
	"\xbf\xef\xbe\xdc\xad\x6e\xc1\xc3\xbc\x67\r\xaa\xba\xa8\xf7\xb6\x62\xa1\x43", /* "選擇要謄寫的卷軸。" */
	"\r\r\r \xb1\x71\xb6\xa4\xa5\xee\xa4\xa4\xbf\xef\xa4\x40\xa6\xec\r \xb7\x51\xad\x6e\xc1\xc3\xbc\x67\r \xaa\x6b\xb3\x4e\xaa\xba\xaa\x6b\xae\x76\xa1\x43", /* "從隊伍中選一位想要謄寫法術的法師。" */
	" \xa8\x53\xa6\xb3\xa5\x69\xa5\x48\r \xc1\xc3\xbc\x67\xaa\xba\r \xa8\xf7\xb6\x62\xa1\x43", /* "沒有可以謄寫的卷軸。" */
	" \xa8\x53\xa6\xb3\xb3\x6f\xa6\xec\xaa\x6b\xae\x76\r \xbb\xdd\xad\x6e\xaa\xba\xa8\xf7\xb6\x62\xa1\x43", /* "沒有這位法師需要的卷軸。" */
	"\r \xb6\xa4\xa5\xee\xa4\xa4\xa8\x53\xa6\xb3\r \xaf\xe0\xc1\xc3\xbc\x67\xa8\xf7\xb6\x62\r \xaa\xba\xaa\x6b\xae\x76\xa1\x43", /* "隊伍中沒有能謄寫卷軸的法師。" */
};

static const StringListProvider kEoB1MenuStringsScribeDOSChineseProvider = { ARRAYSIZE(kEoB1MenuStringsScribeDOSChinese), kEoB1MenuStringsScribeDOSChinese };

static const char *const kEoB1MenuStringsDrop2DOSChinese[3] = {
	" \xbf\xef\xbe\xdc\xad\x6e\xbd\xf0\xa5\x58\r \xaa\xba\xa8\xa4\xa6\xe2\xa1\x43", /* "選擇要踢出的角色。" */
	" \xbd\x54\xa9\x77\xad\x6e\r \xc0\x78\xa6\x73\xb9\x43\xc0\xb8\xb6\xdc\xa1\x48", /* "確定要儲存遊戲嗎？" */
	" \xbd\x54\xa9\x77\xad\x6e\xb8\xfc\xa4\x4a\r \xa6\x73\xc0\xc9\xb6\xdc\xa1\x48", /* "確定要載入存檔嗎？" */
};

static const StringListProvider kEoB1MenuStringsDrop2DOSChineseProvider = { ARRAYSIZE(kEoB1MenuStringsDrop2DOSChinese), kEoB1MenuStringsDrop2DOSChinese };

static const char *const kEoB1MenuStringsHeadDOSChinese[3] = {
	"\xc0\xe7\xa1\x47", /* "營：" */
	"\xb0\xbe\xa6\x6e\xa1\x47", /* "偏好：" */
	"\xb9\x43\xc0\xb8\xbf\xef\xb6\xb5\xa1\x47", /* "遊戲選項：" */
};

static const StringListProvider kEoB1MenuStringsHeadDOSChineseProvider = { ARRAYSIZE(kEoB1MenuStringsHeadDOSChinese), kEoB1MenuStringsHeadDOSChinese };

static const char *const kEoB1MenuStringsPoisonDOSChinese[1] = {
	"\xa4\xa4\xac\x72\xb6\xa4\xad\xfb\r\xb1\x4e\xb7\x7c\xa6\xba\xa4\x60\xa1\x49\r\xa4\xb4\xad\x6e\xa5\xf0\xae\xa7\xa1\x48", /* "中毒隊員將會死亡！仍要休息？" */
};

static const StringListProvider kEoB1MenuStringsPoisonDOSChineseProvider = { ARRAYSIZE(kEoB1MenuStringsPoisonDOSChinese), kEoB1MenuStringsPoisonDOSChinese };

static const char *const kEoB1MenuStringsMgcDOSChinese[2] = {
	"%-18s %1d",
	"\xb3\xd1 %d / %d\xa1\x43  ", /* "剩。" */
};

static const StringListProvider kEoB1MenuStringsMgcDOSChineseProvider = { ARRAYSIZE(kEoB1MenuStringsMgcDOSChinese), kEoB1MenuStringsMgcDOSChinese };

static const char *const kEoB1MenuStringsPrefsDOSChinese[4] = {
	"\xad\xb5\xbc\xd6 %-3s", /* "音樂" */
	"\xad\xb5\xae\xc4 %-3s", /* "音效" */
	"\xb6\x69\xab\xd7\xb1\xf8 %-3s", /* "進度條" */
	"\xb7\xc6\xb9\xab %-3s", /* "滑鼠" */
};

static const StringListProvider kEoB1MenuStringsPrefsDOSChineseProvider = { ARRAYSIZE(kEoB1MenuStringsPrefsDOSChinese), kEoB1MenuStringsPrefsDOSChinese };

static const char *const kEoB1MenuStringsRest2DOSChinese[4] = {
	"%s \xc0\xf2\xb1\x6f %s\xa1\x43\r", /* "獲得。" */
	"%s \xa4\x77\xb0\x4f\xbe\xd0 %s\xa1\x43\r", /* "已記憶。" */
	"%s \xb9\xef %s \xac\x49\xae\x69\xaa\x76\xc0\xf8\xa1\x43\r", /* "對施展治療。" */
	"\xa5\xf0\xae\xa7\xa4\x70\xae\xc9\xa1\x47%-4d", /* "休息小時：" */
};

static const StringListProvider kEoB1MenuStringsRest2DOSChineseProvider = { ARRAYSIZE(kEoB1MenuStringsRest2DOSChinese), kEoB1MenuStringsRest2DOSChinese };

static const char *const kEoB1MenuStringsRest4DOSChinese[1] = {
	"\r\xa9\xc7\xaa\xab\xa6\x62\xaa\xfe\xaa\xf1\xa1\x41\xb5\x4c\xaa\x6b\xa6\x62\xa6\xb9\xa5\xf0\xae\xa7\xa1\x43", /* "怪物在附近，無法在此休息。" */
};

static const StringListProvider kEoB1MenuStringsRest4DOSChineseProvider = { ARRAYSIZE(kEoB1MenuStringsRest4DOSChinese), kEoB1MenuStringsRest4DOSChinese };

static const char *const kEoB1MenuStringsDefeatDOSChinese[1] = {
	"\xbe\xe3\xad\xd3\xb6\xa4\xa5\xee\xb3\xa3\xb3\x51\xc0\xbb\xb1\xd1\xa1\x43\xa8\xb8\xb4\x63\xa4\xf6\xa4\xfa\xb1\x4e\xb5\x4c\xa4\x48\xaa\xfd\xbe\xd7\xa6\x61\xa7\xb9\xa6\xa8\xa5\x4c\xad\xcc\xaa\xba\xad\x70\xb5\x65\xa1\x49\r", /* "整個隊伍都被擊敗。邪惡爪牙將無人阻擋地完成他們的計畫！" */
};

static const StringListProvider kEoB1MenuStringsDefeatDOSChineseProvider = { ARRAYSIZE(kEoB1MenuStringsDefeatDOSChinese), kEoB1MenuStringsDefeatDOSChinese };

static const char *const kEoB1MenuYesNoStringsDOSChinese[2] = {
	"\xac\x4f", /* "是" */
	"\xa7\x5f", /* "否" */
};

static const StringListProvider kEoB1MenuYesNoStringsDOSChineseProvider = { ARRAYSIZE(kEoB1MenuYesNoStringsDOSChinese), kEoB1MenuYesNoStringsDOSChinese };

static const char *const kEoB1CharGuiStringsHpDOSChinese[2] = {
	"\xa9\x52", /* "命" */
	"%3d / %-3d",
};

static const StringListProvider kEoB1CharGuiStringsHpDOSChineseProvider = { ARRAYSIZE(kEoB1CharGuiStringsHpDOSChinese), kEoB1CharGuiStringsHpDOSChinese };

static const char *const kEoB1CharGuiStringsWp1DOSChinese[2] = {
	"\xb8\xa8\xaa\xc5", /* "落空" */
	"\xb6\xc3\xac\xe5", /* "亂砍" */
};

static const StringListProvider kEoB1CharGuiStringsWp1DOSChineseProvider = { ARRAYSIZE(kEoB1CharGuiStringsWp1DOSChinese), kEoB1CharGuiStringsWp1DOSChinese };

static const char *const kEoB1CharGuiStringsWrDOSChinese[4] = {
	"\xa4\xa3\xaf\xe0", /* "不能" */
	"\xb0\xf7", /* "夠" */
	"\xa7\x5f", /* "否" */
	"\xbc\x75\xc3\xc4", /* "彈藥" */
};

static const StringListProvider kEoB1CharGuiStringsWrDOSChineseProvider = { ARRAYSIZE(kEoB1CharGuiStringsWrDOSChinese), kEoB1CharGuiStringsWrDOSChinese };

static const char *const kEoB1CharGuiStringsSt1DOSChinese[6] = {
	"\xa4\xc1\xb4\xab", /* "切換" */
	"\xa6\xba\xa4\x60", /* "死亡" */
	"\xa9\xfc\xb0\x67", /* "昏迷" */
	"\xac\x72(\xbd\x77)", /* "毒緩" */
	"\xa4\xa4\xac\x72", /* "中毒" */
	"\xb3\xc2\xb7\xf4", /* "麻痺" */
};

static const StringListProvider kEoB1CharGuiStringsSt1DOSChineseProvider = { ARRAYSIZE(kEoB1CharGuiStringsSt1DOSChinese), kEoB1CharGuiStringsSt1DOSChinese };

static const char *const kEoB1CharGuiStringsInDOSChinese[4] = {
	"\xa8\xa4\xa6\xe2\xb8\xea\xb0\x54", /* "角色資訊" */
	"\xc5\x40\xa5\xd2", /* "護甲" */
	"\xb8\x67", /* "經" */
	"\xaf\xc5", /* "級" */
};

static const StringListProvider kEoB1CharGuiStringsInDOSChineseProvider = { ARRAYSIZE(kEoB1CharGuiStringsInDOSChinese), kEoB1CharGuiStringsInDOSChinese };

static const char *const kEoB1CharStatusStrings7DOSChinese[1] = {
	"%s \xa5\xa8\xa4\x48\xa4\xa7\xa4\x4f\xae\xf8\xa5\xa2\xa1\x43\r", /* "巨人之力消失。" */
};

static const StringListProvider kEoB1CharStatusStrings7DOSChineseProvider = { ARRAYSIZE(kEoB1CharStatusStrings7DOSChinese), kEoB1CharStatusStrings7DOSChinese };

static const char *const kEoB1CharStatusStrings81DOSChinese[1] = {
	"%s \xb7\x50\xa8\xfc\xa8\xec\xac\x72\xae\xc4\xa1\x49\r", /* "感受到毒效！" */
};

static const StringListProvider kEoB1CharStatusStrings81DOSChineseProvider = { ARRAYSIZE(kEoB1CharStatusStrings81DOSChinese), kEoB1CharStatusStrings81DOSChinese };

static const char *const kEoB1CharStatusStrings9DOSChinese[1] = {
	"%s \xa4\xa3\xa6\x41\xb3\xc2\xb7\xf4\xa1\x49\r", /* "不再麻痺！" */
};

static const StringListProvider kEoB1CharStatusStrings9DOSChineseProvider = { ARRAYSIZE(kEoB1CharStatusStrings9DOSChinese), kEoB1CharStatusStrings9DOSChinese };

static const char *const kEoB1CharStatusStrings131DOSChinese[1] = {
	"%s\xac\x4f%s\xa1\x49\r", /* "是！" */
};

static const StringListProvider kEoB1CharStatusStrings131DOSChineseProvider = { ARRAYSIZE(kEoB1CharStatusStrings131DOSChinese), kEoB1CharStatusStrings131DOSChinese };

static const char *const kEoB1LevelGainStringsDOSChinese[1] = {
	"\x06\x01%s has gained a level of experience.\x06\x0f\r",
};

static const StringListProvider kEoB1LevelGainStringsDOSChineseProvider = { ARRAYSIZE(kEoB1LevelGainStringsDOSChinese), kEoB1LevelGainStringsDOSChinese };

static const char *const kEoB1BookNumbersDOSChinese[5] = {
	"\xa4\x40\xaf\xc5", /* "一級" */
	"\xa4\x47\xaf\xc5", /* "二級" */
	"\xa4\x54\xaf\xc5", /* "三級" */
	"\xa5\x7c\xaf\xc5", /* "四級" */
	"\xa4\xad\xaf\xc5", /* "五級" */
};

static const StringListProvider kEoB1BookNumbersDOSChineseProvider = { ARRAYSIZE(kEoB1BookNumbersDOSChinese), kEoB1BookNumbersDOSChinese };

static const char *const kEoB1MageSpellsListDOSChinese[26] = {
	"",
	"\xc5\x40\xa5\xd2", /* "護甲" */
	"\xbf\x55\xbf\x4e\xa4\xa7\xa4\xe2", /* "燃燒之手" */
	"\xb0\xbb\xb4\xfa\xc5\x5d\xaa\x6b", /* "偵測魔法" */
	"\xc5\x5d\xaa\x6b\xad\xb8\xbc\x75", /* "魔法飛彈" */
	"\xb8\xd1\xc5\xaa\xc5\x5d\xaa\x6b", /* "解讀魔法" */
	"\xc5\x5d\xaa\x6b\xac\xde", /* "魔法盾" */
	"\xb9\x71\xc0\xbb", /* "電擊" */
	"\xc1\xf4\xa7\xce", /* "隱形" */
	"\xb6\x7d\xc2\xea", /* "開鎖" */
	"\xbb\xc4\xb2\x47\xbd\x62", /* "酸液箭" */
	"\xaf\xe4\xb6\xb3", /* "臭雲" */
	"\xc5\x58\xb4\xb2\xc5\x5d\xaa\x6b", /* "驅散魔法" */
	"\xa4\xf5\xb2\x79\xb3\x4e", /* "火球術" */
	"\xb5\x4b\xbd\x62", /* "焰箭" */
	"\xa5\x5b\xb3\x74", /* "加速" */
	"\xa9\x77\xa8\xad\xb3\x4e", /* "定身術" */
	"\xb8\x73\xc5\xe9\xc1\xf4\xa7\xce", /* "群體隱形" */
	"\xb0\x7b\xb9\x71", /* "閃電" */
	"\xa7\x6c\xa6\xe5\xa4\x40\xc4\xb2", /* "吸血一觸" */
	"\xae\xa3\xc4\xdf", /* "恐懼" */
	"\xa6\x42\xad\xb7\xbc\xc9", /* "冰風暴" */
	"\xa5\xdb\xbd\xa7", /* "石膚" */
	"\xac\x72\xb6\xb3", /* "毒雲" */
	"\xc0\x40\xa7\xce\xb4\x48\xa6\x42", /* "錐形寒冰" */
	"\xa9\x77\xa8\xad\xa9\xc7\xaa\xab", /* "定身怪物" */
};

static const StringListProvider kEoB1MageSpellsListDOSChineseProvider = { ARRAYSIZE(kEoB1MageSpellsListDOSChinese), kEoB1MageSpellsListDOSChinese };

static const char *const kEoB1ClericSpellsListDOSChinese[25] = {
	"",
	"\xaf\xac\xba\xd6", /* "祝福" */
	"\xbb\xb4\xab\xd7\xaa\x76\xc0\xf8", /* "輕度治療" */
	"\xb3\x79\xa6\xa8\xbb\xb4\xb6\xcb", /* "造成輕傷" */
	"\xb0\xbb\xb4\xfa\xc5\x5d\xaa\x6b", /* "偵測魔法" */
	"\xa8\xbe\xc5\x40\xa8\xb8\xb4\x63", /* "防護邪惡" */
	"\xa7\x55", /* "助" */
	"\xbf\x56\xa4\x62", /* "燄刃" */
	"\xa9\x77\xa8\xad\xb3\x4e", /* "定身術" */
	"\xbd\x77\xac\x72", /* "緩毒" */
	"\xb3\x79\xad\xb9\xaa\xab", /* "造食物" */
	"\xc5\x58\xb4\xb2\xc5\x5d\xaa\x6b", /* "驅散魔法" */
	"\xc5\x5d\xaa\x6b\xb3\x54", /* "魔法袍" */
	"\xac\xe8\xc3\xab", /* "祈禱" */
	"\xb8\xd1\xb0\xa3\xb3\xc2\xb7\xf4", /* "解除麻痺" */
	"\xad\xab\xab\xd7\xaa\x76\xc0\xf8", /* "重度治療" */
	"\xb3\x79\xa6\xa8\xad\xab\xb6\xcb", /* "造成重傷" */
	"\xa4\xa4\xa9\x4d\xac\x72\xaf\xc0", /* "中和毒素" */
	"\xa8\xbe\xc5\x40\xa8\xb8\xb4\x63\xb8\x73\xc5\xe9", /* "防護邪惡群體" */
	"\xa8\xbe\xb9\x70", /* "防雷" */
	"\xc4\x59\xad\xab\xaa\x76\xc0\xf8", /* "嚴重治療" */
	"\xb3\x79\xa6\xa8\xad\x50\xa9\x52\xb6\xcb", /* "造成致命傷" */
	"\xb5\x4b\xc0\xbb", /* "焰擊" */
	"\xb4\x5f\xac\xa1\xb3\x4e", /* "復活術" */
	"\xb8\x74\xa4\xe2", /* "聖手" */
};

static const StringListProvider kEoB1ClericSpellsListDOSChineseProvider = { ARRAYSIZE(kEoB1ClericSpellsListDOSChinese), kEoB1ClericSpellsListDOSChinese };

static const char *const kEoB1SpellNamesDOSChinese[51] = {
	"",
	"\xc5\x40\xa5\xd2", /* "護甲" */
	"\xbf\x55\xbf\x4e\xa4\xa7\xa4\xe2", /* "燃燒之手" */
	"\xb0\xbb\xb4\xfa\xc5\x5d\xaa\x6b", /* "偵測魔法" */
	"\xc5\x5d\xaa\x6b\xad\xb8\xbc\x75", /* "魔法飛彈" */
	"\xc5\x5d\xaa\x6b\xac\xde", /* "魔法盾" */
	"\xb9\x71\xc0\xbb", /* "電擊" */
	"\xc1\xf4\xa7\xce", /* "隱形" */
	"\xbb\xc4\xb2\x47\xbd\x62", /* "酸液箭" */
	"\xaf\xe4\xb6\xb3", /* "臭雲" */
	"\xc5\x58\xb4\xb2\xc5\x5d\xaa\x6b", /* "驅散魔法" */
	"\xa4\xf5\xb2\x79\xb3\x4e", /* "火球術" */
	"\xb5\x4b\xbd\x62", /* "焰箭" */
	"\xa5\x5b\xb3\x74", /* "加速" */
	"\xa9\x77\xa8\xad\xb3\x4e", /* "定身術" */
	"\xb8\x73\xc5\xe9\xc1\xf4\xa7\xce", /* "群體隱形" */
	"\xb0\x7b\xb9\x71", /* "閃電" */
	"\xa7\x6c\xa6\xe5\xa4\x40\xc4\xb2", /* "吸血一觸" */
	"\xae\xa3\xc4\xdf", /* "恐懼" */
	"\xa6\x42\xad\xb7\xbc\xc9", /* "冰風暴" */
	"\xa5\xdb\xbd\xa7", /* "石膚" */
	"\xac\x72\xb6\xb3", /* "毒雲" */
	"\xc0\x40\xa7\xce\xb4\x48\xa6\x42", /* "錐形寒冰" */
	"\xa9\x77\xa8\xad\xa9\xc7\xaa\xab", /* "定身怪物" */
	"\xaf\xac\xba\xd6", /* "祝福" */
	"\xbb\xb4\xab\xd7\xaa\x76\xc0\xf8", /* "輕度治療" */
	"\xb3\x79\xa6\xa8\xbb\xb4\xb6\xcb", /* "造成輕傷" */
	"\xb0\xbb\xb4\xfa\xc5\x5d\xaa\x6b", /* "偵測魔法" */
	"\xa8\xbe\xc5\x40\xa8\xb8\xb4\x63", /* "防護邪惡" */
	"\xa7\x55", /* "助" */
	"\xbf\x56\xa4\x62", /* "燄刃" */
	"\xa9\x77\xa8\xad\xb3\x4e", /* "定身術" */
	"\xbd\x77\xac\x72", /* "緩毒" */
	"\xb3\x79\xad\xb9\xaa\xab", /* "造食物" */
	"\xc5\x58\xb4\xb2\xc5\x5d\xaa\x6b", /* "驅散魔法" */
	"\xc5\x5d\xaa\x6b\xb3\x54", /* "魔法袍" */
	"\xac\xe8\xc3\xab", /* "祈禱" */
	"\xb8\xd1\xb0\xa3\xb3\xc2\xb7\xf4", /* "解除麻痺" */
	"\xad\xab\xab\xd7\xaa\x76\xc0\xf8", /* "重度治療" */
	"\xb3\x79\xa6\xa8\xad\xab\xb6\xcb", /* "造成重傷" */
	"\xa4\xa4\xa9\x4d\xac\x72\xaf\xc0", /* "中和毒素" */
	"\xa8\xb8\xb4\x63\xa8\xbe\xc5\x40\xb5\xb2\xac\xc9", /* "邪惡防護結界" */
	"\xa8\xbe\xb9\x70\xb9\x71", /* "防雷電" */
	"\xc4\x59\xad\xab\xaa\x76\xc0\xf8", /* "嚴重治療" */
	"\xad\x50\xa9\x52\xb6\xcb", /* "致命傷" */
	"\xb5\x4b\xc0\xbb", /* "焰擊" */
	"\xb4\x5f\xac\xa1\xb3\x4e", /* "復活術" */
	"\xab\xf6\xa4\xe2\xaa\x76\xc0\xf8", /* "按手治療" */
	"",
	"",
	"",
};

static const StringListProvider kEoB1SpellNamesDOSChineseProvider = { ARRAYSIZE(kEoB1SpellNamesDOSChinese), kEoB1SpellNamesDOSChinese };

static const char *const kEoB1MagicStrings1DOSChinese[6] = {
	"\xa4\xa4\xa4\xee\xac\x49\xaa\x6b", /* "中止施法" */
	"\xa4\xa4\xa4\xee\xac\x49\xaa\x6b", /* "中止施法" */
	"\xac\x49\xa6\xb9\xaa\x6b\xb3\x4e\xbb\xdd\xaa\xc5\xa4\xe2\xa1\x43\r", /* "施此法術需空手。" */
	"\xa4\xa3\xaf\xe0\xa6\x50\xae\xc9\xac\x49\xa8\xe2\xad\xd3\xa6\xb9\xc3\xfe\xaa\x6b\xb3\x4e\xa1\x43\r", /* "不能同時施兩個此類法術。" */
	"%s \xac\x49\xae\x69 %s\xa1\x43\r", /* "施展。" */
	"\xa6\x6e\r", /* "好" */
};

static const StringListProvider kEoB1MagicStrings1DOSChineseProvider = { ARRAYSIZE(kEoB1MagicStrings1DOSChinese), kEoB1MagicStrings1DOSChinese };

static const char *const kEoB1MagicStrings2DOSChinese[3] = {
	"\xb5\x4c\xae\xc4\xaa\x47\r", /* "無效果" */
	"%s \xb3\x51\xa4\xc0\xb8\xd1\xa1\x49\r", /* "被分解！" */
	"\xb6\xa4\xa5\xee\xb3\x51\xa6\xba\xa4\x60\xaa\x6b\xb3\x4e\xc0\xbb\xa4\xa4\xa1\x49\r", /* "隊伍被死亡法術擊中！" */
};

static const StringListProvider kEoB1MagicStrings2DOSChineseProvider = { ARRAYSIZE(kEoB1MagicStrings2DOSChinese), kEoB1MagicStrings2DOSChinese };

static const char *const kEoB1MagicStrings3DOSChinese[6] = {
	"\xb9\xef\xad\xfe\xa6\xec\xa8\xa4\xa6\xe2\xac\x49\xaa\x6b\xa1\x48", /* "對哪位角色施法？" */
	"\r\xa6\x6e\r", /* "好" */
	"\r\xac\x49\xaa\x6b\xa4\xa4\xa4\xee\xa1\x43\r", /* "施法中止。" */
	"%s \xaa\xba %s \xaa\x6b\xb3\x4e\xae\xf8\xa5\xa2\xa1\x43\r", /* "的法術消失。" */
	"%s \xa7\xf0\xc0\xbb\xa9\xc7\xaa\xab\xb8\xa8\xaa\xc5\xa1\x43\r", /* "攻擊怪物落空。" */
	"%s \xa5\xb2\xb6\xb7\xa6\x62\xab\x65\xb1\xc6\xa4\x7e\xaf\xe0\xa7\xf0\xc0\xbb\xa1\x49\r", /* "必須在前排才能攻擊！" */
};

static const StringListProvider kEoB1MagicStrings3DOSChineseProvider = { ARRAYSIZE(kEoB1MagicStrings3DOSChinese), kEoB1MagicStrings3DOSChinese };

static const char *const kEoB1MagicStrings4DOSChinese[1] = {
	"\xb5\x4c\xae\xc4\xaa\x47\xa1\x43\r", /* "無效果。" */
};

static const StringListProvider kEoB1MagicStrings4DOSChineseProvider = { ARRAYSIZE(kEoB1MagicStrings4DOSChinese), kEoB1MagicStrings4DOSChinese };

static const char *const kEoB1MagicStrings6DOSChinese[1] = {
	"%s \xa4\x77\xa6\xb3\xb0\xaa\xb0\xf2\xc2\xa6\xc5\x40\xa5\xd2\xa1\x43\r", /* "已有高基礎護甲。" */
};

static const StringListProvider kEoB1MagicStrings6DOSChineseProvider = { ARRAYSIZE(kEoB1MagicStrings6DOSChinese), kEoB1MagicStrings6DOSChinese };

static const char *const kEoB1MagicStrings7DOSChinese[5] = {
	"\xa4\x40", /* "一" */
	"\xa4\x47", /* "二" */
	"\xa4\x54", /* "三" */
	"\xa5\x7c", /* "四" */
	"\xa4\xad", /* "五" */
};

static const StringListProvider kEoB1MagicStrings7DOSChineseProvider = { ARRAYSIZE(kEoB1MagicStrings7DOSChinese), kEoB1MagicStrings7DOSChinese };

static const char *const kEoB1MagicStrings8DOSChinese[3] = {
	"%s \xa8\xad\xa4\x57\xa9\xd2\xa6\xb3\xaa\x6b\xb3\x4e\xb3\x51\xc5\x58\xb4\xb2\xa1\x43\r", /* "身上所有法術被驅散。" */
	"\xb6\xa4\xa5\xee\xa4\x77\xb3\x51\xaf\xac\xba\xd6\xa1\x49\r", /* "隊伍已被祝福！" */
	"\xc0\xb0\xa7\x55\xaa\x6b\xb3\x4e\xa5\xa2\xb1\xd1\xa1\x49\r", /* "幫助法術失敗！" */
};

static const StringListProvider kEoB1MagicStrings8DOSChineseProvider = { ARRAYSIZE(kEoB1MagicStrings8DOSChinese), kEoB1MagicStrings8DOSChinese };

static const char *const kEoB1MagicStrings9DOSChinese[1] = {
	"%s\xa4\x77\xb3\x51\xa5\xdb\xbd\xa7\xab\x4f\xc5\x40\xa1\x43\r", /* "已被石膚保護。" */
};

static const StringListProvider kEoB1MagicStrings9DOSChineseProvider = { ARRAYSIZE(kEoB1MagicStrings9DOSChinese), kEoB1MagicStrings9DOSChinese };

static const char *const kEoB1ManWordDOSChinese[31] = {
	"\xa7\xf0\xc0\xbb", /* "攻擊" */
	"\xb5\x75", /* "短" */
	"\xb1\xc6", /* "排" */
	"\xaa\x5a\xbe\xb9", /* "武器" */
	"\xac\x59\xa8\xc7", /* "某些" */
	"\xb0\x7d", /* "陣" */
	"\xab\xe1", /* "後" */
	"\xa5\x69", /* "可" */
	"\xc2\xf7\xb6\x7d", /* "離開" */
	"\xa6\x61\xab\xb0", /* "地城" */
	"\xb4\xe5\xbc\xd0", /* "游標" */
	"\xa5\x5c\xaf\xe0", /* "功能" */
	"\xb8\xea\xb0\x54", /* "資訊" */
	"\xc5\xe3\xa5\xdc", /* "顯示" */
	"\xa4\x55\xa4\xe8", /* "下方" */
	"\xa9\x50\xb3\xf2", /* "周圍" */
	"\xb5\x4c\xbc\x7e", /* "無憂" */
	"\xa6\x61\xba\xeb", /* "地精" */
	"\xaa\xaa\xae\x76", /* "牧師" */
	"\xaf\xab\xaf\xb5", /* "神秘" */
	"\xad\xab\xc0\xbb", /* "重擊" */
	"\xb1\x6a\xb0\xb7", /* "強健" */
	"\xa8\xcf\xa5\xce", /* "使用" */
	"\xb0\xed\xb6\xb4", /* "堅韌" */
	"\xb0\x5d\xb4\x49", /* "財富" */
	"\xa7\xc5\xae\x76", /* "巫師" */
	"\xa9\x78\xad\xfb", /* "官員" */
	"\xc2\x79\xa4\xfc", /* "獵犬" */
	"\xc2\x5a\xa4\x48", /* "擾人" */
	"\xbf\x55\xbf\x4e", /* "燃燒" */
	"",
};

static const StringListProvider kEoB1ManWordDOSChineseProvider = { ARRAYSIZE(kEoB1ManWordDOSChinese), kEoB1ManWordDOSChinese };

static const char *const kEoB1ManPromptDOSChinese[1] = {
	"\r\r\r\r\xa6\x62\xbc\xd0\xa6\xb3\xa6\xb9\xb2\xc5\xb8\xb9\xaa\xba\xad\xb6\xa4\x57...\r\r\xa7\xe4\xa8\xec\xb2\xc4%d\xa6\xe6\r\xbf\xe9\xa4\x4a\xb2\xc4%d\xad\xd3\xa6\x72\r", /* "在標有此符號的頁上找到第行輸入第個字" */
};

static const StringListProvider kEoB1ManPromptDOSChineseProvider = { ARRAYSIZE(kEoB1ManPromptDOSChinese), kEoB1ManPromptDOSChinese };

static const char *const kEoB1MonsterDistAttStringsDOSChinese[5] = {
	"%s \xb3\x51\xad\xab\xb6\xcb\xb3\x4e\xc0\xbb\xa4\xa4\xa1\x49\r", /* "被重傷術擊中！" */
	"\xb6\xa4\xa5\xee\xb3\x51\xba\xeb\xaf\xab\xbd\xc4\xc0\xbb\xa5\xb4\xa4\xa4\xa1\x49\r", /* "隊伍被精神衝擊打中！" */
	"\xb3\xc2\xb7\xf4", /* "麻痺" */
	"\xa4\xa4\xac\x72", /* "中毒" */
	"\xb3\xc2\xb7\xf4", /* "麻痺" */
};

static const StringListProvider kEoB1MonsterDistAttStringsDOSChineseProvider = { ARRAYSIZE(kEoB1MonsterDistAttStringsDOSChinese), kEoB1MonsterDistAttStringsDOSChinese };

static const char *const kEoB1NpcPresetsNamesDOSChinese[9] = {
	"\xa6\x77\xb6\xae", /* "安雅" */
	"\xb2\xa6\xbc\xda\xa9\xd4\xa9\x69", /* "畢歐拉姆" */
	"\xb3\xcd\xa9\xd4\xb4\xb5", /* "凱拉斯" */
	"\xa5\xec\xc1\xa2\xb2\xfa\xb6\xae", /* "伊蕾莉雅" */
	"\xae\xf5\xa9\xd4", /* "泰拉" */
	"\xb3\xb3\xbc\x77", /* "陶德" */
	"\xb6\xf0\xa4\xe0", /* "塔戈" */
	"\xa6\x68\xad\xdb", /* "多倫" */
	"\xb3\xcd\xb9\xc5", /* "凱嘉" */
};

static const StringListProvider kEoB1NpcPresetsNamesDOSChineseProvider = { ARRAYSIZE(kEoB1NpcPresetsNamesDOSChinese), kEoB1NpcPresetsNamesDOSChinese };
